[tool.poetry]
name = "db_tests"
version = "0.1.0"
description = ""
authors = ["Piotr Styczyński <piotr@styczynski.in>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.1.2"
"testing.postgresql" = "^1.3.0"
SQLAlchemy = "^1.4.37"
psycopg2 = "^2.9.3"
pgsanity = "^0.2.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
