CREATE FUNCTION nuclseq_len(nucl_seq)
    RETURNS INTEGER
    AS 'MODULE_PATHNAME'
    LANGUAGE C IMMUTABLE STRICT;

CREATE FUNCTION nuclseq_content(nucl_seq, cstring)
    RETURNS DOUBLE PRECISION
    AS 'MODULE_PATHNAME'
    LANGUAGE C IMMUTABLE STRICT;

CREATE FUNCTION nuclseq_complement(nucl_seq)
    RETURNS nucl_seq
    AS 'MODULE_PATHNAME'
    LANGUAGE C IMMUTABLE STRICT;

CREATE FUNCTION nuclseq_reverse(nucl_seq)
    RETURNS nucl_seq
    AS 'MODULE_PATHNAME'
    LANGUAGE C IMMUTABLE STRICT;