name: CI
on: [push]
jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack about build
        if: success()
        id: slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: build
          status: STARTING
          color: warning
      - uses: actions/checkout@v2
      - name: Install Ubuntu dependencies
        run: sudo apt-get install -y libseqlib-dev postgresql postgresql-server-dev-all
      - name: Build Postgres extension
        run: mkdir build && cd build && cmake .. && make
      - name: Notify slack about build success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: build
          status: SUCCESS
          color: good
      - name: Notify slack about build fail
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          message_id: ${{ steps.slack.outputs.message_id }}
          channel: build
          status: FAILED
          color: danger
