version: "3.9"
services:
  postgres:
    container_name: db
    build:
      context: ../..
      dockerfile: ./ops/docker/Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bioseqdb
      PGDATA: /pgtmpfs
    tmpfs:
      - /pgtmpfs
    networks:
      - development

networks:
  development:
    name: development