FROM postgres:14-bullseye

LABEL maintainer="bioseqdb - https://github.com/covid-genomics/bioseqdb"


RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
      autoconf \
      automake \
      autotools-dev \
	  build-essential \
      ca-certificates \
      cmake \
      g++ \
      git \
      make \
      postgresql-server-dev-14 \
	  libbz2-dev \
	  zlib1g-dev \
	  liblzma-dev \
    libpq-dev \
    postgresql-server-dev-all

RUN apt-get install -y python3 python3-pip && pip install pip poetry --upgrade
ADD . /bioseqdb
WORKDIR /bioseqdb

RUN apt-get install -y fswatch

RUN chmod u+x /bioseqdb/ops/docker/dev_pg_docker_entrypoint.sh 
ENTRYPOINT ["bash", "/bioseqdb/ops/docker/dev_pg_docker_entrypoint.sh"]

#mkdir build && cd build && cmake .. && make && make install

# .sh or .sql files from docker-entrypoint-initdb.d
# are run right after db is created
COPY ./ops/docker/entrypoint.sql /docker-entrypoint-initdb.d/