DROP EXTENSION IF EXISTS bioseqdb;
CREATE EXTENSION bioseqdb;

CREATE TABLE dataset (
    id serial primary key not null,
    seq nuclseq not null
);

INSERT INTO dataset (seq) VALUES (nuclseq_in('ACTATCTATCTACTATCTATCTTCTTATCTTAACTATCTATCTTCTTA'));
INSERT INTO dataset (seq) VALUES (nuclseq_in('ACTATCAAAAAATCTATCTTCTTATCTAACCCCCAAATAACTATCTATCTTCTTA'));
INSERT INTO dataset (seq) VALUES (nuclseq_in('ACTATCTATCTACTATCTATCTTCTTATCTTAACTATCTATCTTCTTAAAAAAAAAAAAACTATCTATCTACTATCTATCTTCTTATCTTAACTATCTATCTTCTTA'));
INSERT INTO dataset (seq) VALUES (nuclseq_in('ACTCATATCCCCCATCCCCTATCTACTATTATTATATCTATCTTCTTATATATTCTTAACTATCTATCTTCTTA'));
INSERT INTO dataset (seq) VALUES (nuclseq_in('CCCACACTATCTATCTACTATCTATCTTCTTATCTTAACTATCTATCTTCTTACCCCA'));
INSERT INTO dataset (seq) VALUES (nuclseq_in('CCACCACCACCACCACCAATTATATATATTA'));
INSERT INTO dataset (seq) VALUES (nuclseq_in('ACCTACTTTTTTATATATA'));
INSERT INTO dataset (seq) VALUES (nuclseq_in('ACTAACTAACTAAAAAACTAGCACAA'));
INSERT INTO dataset (seq) VALUES (nuclseq_in('AATCTATCTATGCTTATCTATA'));
INSERT INTO dataset (seq) VALUES (nuclseq_in('AACTTTTTTTTTTTTTTTTTTTA'));

ALTER DATABASE bioseqdb SET log_statement = 'all';

/*SELECT * FROM bwa_opts();*/

/*SELECT * FROM nuclseq_reverse(nuclseq_in('ACTA'));*/

SELECT * FROM nuclseq_search_bwa(nuclseq_in('CTACTATCTATCTTCTTAT'), 'SELECT id, seq FROM dataset');